//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO_Messenger.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter your password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Enter phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\d{9})$", ErrorMessage = "Wrong mobile")]
        public string PhoneNumber { get; set; }


        [Required(ErrorMessage = "Enter your email adress")]
        [RegularExpression(".+\\@.+\\...+",
            ErrorMessage ="Wrong email")]
        public string EmialAdress { get; set; }
    }
}
